### ISSUE TITLE
content-type should default to "binary/octet-stream" if not set on upload

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#697]
**Describe the bug**
Uploading an object without setting the content type explicitly results in head-object returning:
```
    "ContentType": "text/plain; charset=utf-8",
```

When it should return:
```
    "ContentType": "binary/octet-stream",
```
to match AWS behavior

**To Reproduce**
```
# aws s3 mb s3://test
# aws s3 cp ./testfile s3://test/testfile
# aws s3api head-object --bucket test --key testfile
{
    "Restore": "",
    "LastModified": "2024-07-29T14:44:23+00:00",
    "ContentLength": 4862,
    "ETag": "\"2aa6c33b2de8bc9a735111cf3bccf071\"",
    "ContentType": "text/plain; charset=utf-8",
    "Metadata": {},
    "StorageClass": ""
}
```

**Expected behavior**
expected
```
    "ContentType": "binary/octet-stream",
```

**Server Version**
main build
```
Version  : v1.0.4
Build    : 55c7109
BuildTime: 2024-07-30_05:00:18PM
```

**Additional context**
```
# aws --version
aws-cli/2.13.11 Python/3.11.4 Darwin/23.5.0 exe/x86_64 prompt/off
```

**Comment by ramkicse** [comment]
i created presigned URL 
https://ramki.in/s3/dir/sd_results.csv?response-content-disposition=sd_results.csv&response-content-type=application%2Foctet-stream&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240801T060110Z&X-Amz-SignedHeaders=host&X-Amz-Credential=ramki%2F20240801%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Expires=600&X-Amz-Signature=68639e9f3e715660bfd681797e4ee7bcd7ba6779ad3780f2993fe6125253faba


in presigned url i set response content type as **octet-stream**
![Screenshot from 2024-08-01 12-08-29](https://github.com/user-attachments/assets/7d227b1a-b8c6-4b52-81b7-b38501fb0b9b)

still i got **text/plain** in response and my browser shows the content, instead of download it
![image](https://github.com/user-attachments/assets/47d3f71a-9e5a-47a6-ad34-4b271909c949)

**Comment by ramkicse** [comment]
i want presigned url which browser can download the files
thanks
