### ISSUE TITLE
concurrent uploading the same object sometimes results in the exception ExistingObjectIsDirectory

### ISSUE THREAD

**Issue by tonyipm** [versity/versitygw#854]
**Describe the bug**
concurrent uploading the same object sometimes results in the exception ExistingObjectIsDirectory. See script below

**To Reproduce**
#!/bin/bash

printf "abc\n" >body.txt

for ((ii=1; ii<=10; ii++)); do
    aws s3api put-object --endpoint-url http://10.60.0.32:7070/ --region us-east-1 --bucket test --key=object1 --body body.txt &
done

wait

OUTPUT:
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}

An error occurred (ExistingObjectIsDirectory) when calling the PutObject operation: Existing Object is a directory.
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}
{
    "ETag": "0bee89b07a248e27c83fc3d5951213c1"
}

**Expected behavior**
object upload to complete without error

**Server Version**
git clone from 25 sep 

**Additional context**

**Comment by benmcclelland** [comment]
Ah! I wonder if this was the same root issue as #392. Thank you for the reproducer. This made it much easier to chase down the root cause. The problem is that each upload tries to remove the old file (if it exists) and move in the new upload in its place. But this remove and move is not atomic and opens up a race window with simultaneous uploads. We can fix this by either retrying on this error, or returning success since with this race it is not deterministic which upload should win.
